CREATE TABLE IF NOT EXISTS mapped_urls (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url_source VARCHAR(255) NOT NULL,
    url_mapped VARCHAR(255) NOT NULL UNIQUE,
    click_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS click_analytics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mapped_url_id VARCHAR(255) NOT NULL,
    clicked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


